* intro

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [2]:
#creating tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#number of dimensions
scalar.ndim

0

In [4]:
#create vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
#check dim
vector.ndim

1

In [6]:
#create matrix
matrix = tf.constant([[10,8],
                     [9,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 9, 10]])>

In [7]:
#check number of dimension
matrix.ndim

2

In [8]:
#another matrix
another_matrix = tf.constant([[10.,5.],
                             [2.,4.],
                             [6.,3.]], dtype = tf.float16) #specifying the dtype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 2.,  4.],
       [ 6.,  3.]], dtype=float16)>

In [9]:
#dim number
another_matrix.ndim

2

total number is dimension is how many elements is in the shape

In [10]:
#tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                      [10, 11, 12]],
                      [[13,14,15],
                      [16,17,18]]]) 
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
#dim check
tensor.ndim

3

* Scalar = single number
* vector = number with direction
* matrix = 2d array of numbers
* tensor = n-dimensional

* 0 dimensional tensor is a scalar, 1 dimensional tensor is vector

### tensor with tf.variable

In [12]:
#same tensor with tf.variable()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [13]:
#does not work
#change element in changeable
#changeable_tensor[0] = 7
#changeable_tensor

In [14]:
#trying using .asign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [15]:
#does not work
#changing unchangeable
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

## random tensor's, some arbitary size with random number

In [16]:
random_1 = tf.random.Generator.from_seed(42) #seed for reproducability
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

#are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order of elements

In [17]:
#shuffle tensor (for shuffling data in order which doesn't affect learning)
not_shuffled = tf.constant([[10, 9],
                           [4,4],
                           [21,54]])
not_shuffled.ndim
not_shuffled

#shuffle non shuffled
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 4,  4],
       [21, 54]])>

In [18]:
#shuffle non shuffled
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [21, 54],
       [ 4,  4]])>

In [19]:
#shuffle non shuffled
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled, seed = 42) #operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 4,  4],
       [21, 54]])>

In [20]:
#shuffle tensor (for shuffling data in order which doesn't affect learning)
not_shuffled = tf.constant([[40, 945],
                           [434,42],
                           [214,542]])
not_shuffled.ndim
not_shuffled

tf.random.set_seed(3)

#shuffle non shuffled
tf.random.shuffle(not_shuffled, seed=3)

#if you want tensor's to be in same order use both global and operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[434,  42],
       [ 40, 945],
       [214, 542]])>

In [21]:
tf.ones([23,4]) #tensor of all ones

<tf.Tensor: shape=(23, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros(shape=(2,3)) #tensor's with zeros

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### numpy to tensor

numpy array vs tensor * tensor can run on gpu with faster calculatio

In [23]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

#X = tf.constant(some_matrix), X = capital 
#y = tf.constant(vector) y = non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [24]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

### get info

* shape
* rank
* Axis or dimension
* Size


In [25]:
#rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [27]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
2*3*4*5

120

In [29]:
#get various attributes
print("datatype of all element", rank_4_tensor.dtype)
print("number of dimension (rank)", rank_4_tensor.ndim)
print("shape of tensor", tf.size(rank_4_tensor).numpy())
print("element on 0 axis", rank_4_tensor.shape[0])
print("elements on last axis", rank_4_tensor.shape[-1])
print("elements on last axis", rank_4_tensor.shape)

datatype of all element <dtype: 'float32'>
number of dimension (rank) 4
shape of tensor 120
element on 0 axis 2
elements on last axis 5
elements on last axis (2, 3, 4, 5)


### Indexing Tensors

* can be indexed like python list

In [30]:
#get first 2 elements
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
#get first element from each dimension from each index except the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
#create rank 2 tensor
rank_2_tensor = tf.constant([[2,3],
                            [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [33]:
#get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

In [34]:
#add extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[3],
        [4]]])>

In [35]:
#alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[3],
        [4]]])>

In [36]:
#expand 0 axis
tf.expand_dims(rank_2_tensor, axis=0) #0 to add on the first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [3, 4]]])>

### Manuplulation of Tensors

#### Basic Operations

* Two rules for matrix multiplication
* inner dimension must match
* Resulting matrix has shape of inner dimension

In [37]:
#add value to tensor using addition operation
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [38]:
#original tensor does not change
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [39]:
#multiply
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]])>

In [40]:
#subtraction
tensor - 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 4],
       [0, 1]])>

In [41]:
#tensorflow built in function
#use tf.math.multiply to use with gpu
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [42]:
tf.add(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 10],
       [ 6,  7]])>

In [43]:
tf.subtract(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]])>

In [44]:
tf.divide(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.33333333, 2.33333333],
       [1.        , 1.33333333]])>

### Matrix Multiplication

In [45]:
#matrix multiplication

tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [46]:
# matrix multiplication with python
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [47]:
tensor.shape

TensorShape([2, 2])

In [48]:
#create tensor of 3 x 2
X = tf.constant([[1,2],
                [3,4],
                [5,6]])

Y = tf.constant([[7,8],
                [9,10],
                [11,12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [49]:
#DOES NOT WORK
# trying matmul
#tf.matmul(X,Y)

In [50]:
#change shape of tensor
Y = tf.reshape(Y, shape=(2,3))
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [51]:
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [52]:
tf.matmul(X, Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

**dOT PRODUCT**

In [53]:
# Perform dot on X AND Y (requires transpose)
tf.tensordot(tf.transpose(X), tf.transpose(Y), axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 103],
       [100, 136]])>

In [54]:
#create a new tensor (float 32)
B = tf.constant([1.2,1.4])
B.dtype

tf.float32

In [55]:
C = tf.constant([1,2])
C.dtype

tf.int32

In [56]:
#from float 32 to float 16
D = tf.cast(B, dtype = tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 1.4], dtype=float16)>

In [57]:
#from int32 to float32
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

#### Aggregation

In [58]:
D = tf.constant([-2, -3])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -3])>

In [59]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

##### Forms of aggregation

* Minimum
* Maximum
* Mean
* Sum

In [60]:
#create tensor with 0 to 100
E = tf.constant(np.random.randint(0,100 ,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([43, 54, 63, 52, 92, 20, 50, 85, 21, 46, 26, 29, 21, 16,  7, 76, 63,
       35, 74, 75, 82, 52, 28, 25, 23, 32,  0, 34, 77, 13, 39, 28, 13, 87,
       65, 95, 48, 89, 46, 31, 26, 97, 43, 31, 99, 85, 98, 57, 92,  5])>

In [61]:
tf.size(E), E.shape , E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [62]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [63]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [64]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [65]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2488>

In [66]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.501621>

## Stat's Module

In [67]:
#pip install --upgrade tensorflow-probability

In [68]:
#import tensorflow_probability as tfp

In [69]:
#tfp.stats.variance(E)

In [70]:
#E = tf.cast(E, dtype=tf.float32)
#tfp.stats.stddev(E)

#### Positional Maximum and minimum

In [71]:
#create a new tensor to find positional minimum and maximum

tf.random.set_seed(42)
F = tf.random.uniform(shape=[100])
F

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043,
       0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
       0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ,
       0.28128064, 0.31513572, 0.60670924, 0.7498598 , 0.5016055 ,
       0.18282163, 0.13179815, 0.64636123, 0.9559475 , 0.6670735 ,
       0.30755

In [72]:
#find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [73]:
#index on our largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.97803545>

In [74]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.97803545>

In [75]:
F[tf.argmin(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [76]:
#check for equality
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [77]:
F[tf.argmin(F)] 

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeez tensor

In [78]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [79]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [80]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

#### One Hot Encoding

In [81]:
#create list of indices
some_list = [0,1,2,3] #red, blue, green, purple
tf.one_hot(some_list,4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [82]:
#specify custom values for one hot encoding
tf.one_hot(some_list, depth = 4, on_value = "Hey I love deep learning", off_value="I also like python")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Hey I love deep learning', b'I also like python',
        b'I also like python', b'I also like python'],
       [b'I also like python', b'Hey I love deep learning',
        b'I also like python', b'I also like python'],
       [b'I also like python', b'I also like python',
        b'Hey I love deep learning', b'I also like python'],
       [b'I also like python', b'I also like python',
        b'I also like python', b'Hey I love deep learning']], dtype=object)>

In [83]:
# squaring, log, square root
H = tf.range(1,10)

In [84]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [85]:
#Square Root (method requires non into)
tf.math.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [86]:
#find log
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#### tensor flow and numpy


In [87]:
# create tensor from numpy array
J = tf.constant(np.array([3.,7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [88]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [89]:
#convert tensor J to numpy array
J.numpy, type(J.numpy())

(<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>>,
 numpy.ndarray)

In [90]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [93]:
#the default type of each
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

#### Gpu

In [95]:
tf.config.list_physical_devices("GPU")

[]